name: Push-to-EC2
on:
  push:
    branches:
      - production
jobs:
  build:
    name: Github-Build-CopyCode
    # runs-on: ubuntu-latest
    runs-on: build
    environment: build
    steps:
      - name: basic commands
        run: |
          uname -r
          hostname
          cat /etc/os-release
          pwd
          date
          echo "I like Vadapav" > build.txt
 
  prod:
    needs: build
    name: Github-test-CopyCode
    #runs-on: ubuntu-latest
    runs-on: prod
    environment: prod
    steps:
      - name: Checkout the files
        uses: actions/checkout@v2
      - name: Deploy to prod
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.AWS_KEY }}
          SOURCE: "/"
          ARGS: "-rltgoDzvO --delete"
          REMOTE_HOST: ${{ secrets.HOST_DNS }}
          REMOTE_USER: ${{ secrets.AWS_USERNAME }}
          TARGET: ${{ secrets.TARGET_DIR }}
    
