name: Push-to-EC2
on:
  push:
    branches:
      - production
jobs:
  build:
    name: Github-Build-CopyCode
    # runs-on: ubuntu-latest
    runs-on: build
    environment: build
    steps:
      - name: basic commands
        run: |
          uname -r
          hostname
          cat /etc/os-release
          pwd
          date
          echo "I like Vadapav" > build.txt
  test:
    needs: build
    name: Github-prod-CopyCode
    #runs-on: ubuntu-latest
    runs-on: test
    environment: test
    steps:
      - name: basic commands
        run: |
          uname -r
          hostname
          cat /etc/os-release
          pwd
          date
          echo "I like Vadapav" > prod.txt
  prod:
    needs: test
    name: Github-test-CopyCode
    #runs-on: ubuntu-latest
    runs-on: prod
    environment: prod
    steps:
      - name: basic commands
        run: |
          uname -r
          hostname
          cat /etc/os-release
          pwd
          date
          echo "I like Vadapav" > test.txt
          sudo apt update -y
          sudo apt install apache2 -y
          sudo chmod -R a+rwx /var/www/html
          sudo echo "testing CICD Pipeline" > /var/www/html/index.html
      - name: Deploy to prod
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.AWS_KEY }}
          SOURCE: "/"
          ARGS: "-rltgoDzvO --delete"
          REMOTE_HOST: ${{ secrets.HOST_DNS }}
          REMOTE_USER: ${{ secrets.AWS_USERNAME }}
          TARGET: ${{ secrets.TARGET_DIR }}
          EXCLUDE: "/"
